/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarArticulo.java
 *
 * Created on 26-ago-2013, 21:25:48
 */

package puntodeventa.admin.PrincipalAdmin;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane.*;
import puntodeventa.inicio.conexioninicio;
import java.sql.*;
import javax.swing.JRootPane;
/**
 *
 * @author alberto
 */
public class AgregarProducto extends javax.swing.JFrame {

    /** Creates new form AgregarArticulo */
    public AgregarProducto() {
        initComponents();
        this.setSize(700, 330);
        this.setLocationRelativeTo(null); //Centra la ventana Splash
        
getRootPane().setWindowDecorationStyle(JRootPane.NONE);//elimina botones de cerra, minimizar
//AWTUtilities.setWindowOpacity (this,0.5f);
        
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel23 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jComboBox13 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        preciofv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbfv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        medidafv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        marcafv = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        namefv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        desfv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        marcafv1 = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        nombmarfv = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        jLabel119.setText("Codigo de barras");

        jLabel120.setText("Marca");

        jButton24.setText("Agregar Producto");

        jLabel121.setText("Nombre");

        jLabel122.setText("Descripcion");

        jLabel123.setText("Unidad de medida");

        jLabel124.setText("Precio                         $");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel119)
                            .addComponent(jLabel120)
                            .addComponent(jLabel121)
                            .addComponent(jLabel122))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField75, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jTextField74, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel123)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel124)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField77)
                            .addComponent(jTextField76, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                    .addComponent(jButton24))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel119)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel123)
                    .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel120)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel124))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel121)
                    .addComponent(jTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel122)
                        .addGap(28, 28, 28)
                        .addComponent(jButton24))
                    .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntodeventa/admin/images/fondo.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Precio     $");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 23, 51, -1));

        preciofv.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel3.add(preciofv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 72, -1));

        jLabel8.setText("Seleccione el departamento de la marca");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 191, -1, -1));

        jButton1.setText("Agregar Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, -1, -1));

        jLabel3.setText("Codigo de barras");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));
        jPanel3.add(cbfv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 109, -1));

        jLabel5.setText("Medida");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 23, -1, -1));
        jPanel3.add(medidafv, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 46, 85, -1));

        jLabel4.setText("Marca");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        marcafv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcafvActionPerformed(evt);
            }
        });
        marcafv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marcafvFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcafvFocusLost(evt);
            }
        });
        marcafv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                marcafvAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(marcafv, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 77, -1, -1));

        jLabel1.setText("Nombre");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));
        jPanel3.add(namefv, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 108, 159, -1));

        jLabel2.setText("Descripcion");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 49, -1, -1));
        jPanel3.add(desfv, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 171, -1));

        jLabel7.setText("Departamento");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 150, -1, -1));

        marcafv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcafv1ActionPerformed(evt);
            }
        });
        marcafv1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marcafv1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                marcafv1FocusLost(evt);
            }
        });
        marcafv1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                marcafv1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(marcafv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 147, -1, -1));

        jLabel56.setText("Nombre:");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, -1, -1));
        jPanel3.add(nombmarfv, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 188, 128, -1));

        jButton10.setText("Agregar Marca");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 187, -1, -1));

        jLabel55.setText("Nombre:");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 232, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 229, 101, -1));

        jButton11.setText("Agregar Departamento");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 228, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntodeventa/admin/images/fondo.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcafvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcafvActionPerformed

    }//GEN-LAST:event_marcafvActionPerformed

    private void marcafvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcafvFocusGained
        marcafv.removeAllItems();
        conexioninicio ci=new conexioninicio();
        ci.conectar();
        try{
            Connection con=DriverManager.getConnection(ci.getURl(), ci.getLogin(), ci.getPassword());
            //  System.out.println("Conexion a la base de datos cliente realizada con exito! ");
            Statement stmt=con.createStatement();

            ResultSet rs= stmt.executeQuery( "SELECT idmarca,nombremar FROM tienda.marca where iddepartamento='"+( marcafv1.getSelectedIndex()+1)+"' ;");
            //obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd=rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas=rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las columnas

            // Creando las filas para el Jtable
            while(rs.next()){
                Object[] fila=new Object[cantidadColumnas];
                for(int i=1;i<cantidadColumnas;i++){
                    marcafv.addItem(rs.getObject(i+1));

                }

            }
            rs.close();
            con.close();

        } catch(Exception e) {

            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",
                    JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_marcafvFocusGained

    private void marcafvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcafvFocusLost

}//GEN-LAST:event_marcafvFocusLost

    private void marcafvAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_marcafvAncestorAdded
        // TODO add your handling code here:
}//GEN-LAST:event_marcafvAncestorAdded

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try
                {
                    //checar si se ha escrito el nombre de  la amrca
                    if (nombmarfv.getText().length() > 0  )
                    {
                        // Si el usuario si fue validado correctamente
                        if(! verificarProducto( nombmarfv.getText(), ( Integer.toString(marcafv1.getSelectedIndex()+1) )) )    //enviar datos a validar
                        {

                                    conexioninicio ci = new conexioninicio();
        Connection con=null;
        try{

                con=DriverManager.getConnection(ci.getURl(), ci.getLogin(), ci.getPassword());
                String cadenasql = "insert into tienda.marca(idmarca,nombremar,iddepartamento) values(NULL,'"+ nombmarfv.getText().toUpperCase()+"','"+ (marcafv1.getSelectedIndex()+1)+"')";
                Statement stmt = con.createStatement();
                stmt.executeUpdate(cadenasql);
                JOptionPane.showMessageDialog(null,"Registro exitoso!","",JOptionPane.ERROR_MESSAGE);
                nombmarfv.setText("");
        }

        catch(SQLException e) {

            JOptionPane.showMessageDialog(null,"La marca ya esta registrada","Error",JOptionPane.ERROR_MESSAGE);
        }


                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Esta marca ya se encuentra registrada e el departamento");

                        }

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Escriba el nombre de la marca.\n" +
                            "");
                    }

                } catch (Exception e)
                {
                }




        // TODO add your handling code here:
}//GEN-LAST:event_jButton10ActionPerformed

     boolean verificarProducto(String elUsr, String elPw)  throws IOException
    {
        try
        {
            Connection unaConexion  = DriverManager.getConnection ("jdbc:mysql://localhost/tienda","root", "");
            // Preparamos la consulta
            Statement instruccionSQL = unaConexion.createStatement();
            ResultSet resultadosConsulta = instruccionSQL.executeQuery ("SELECT * FROM marca WHERE nombremar='"+elUsr+"' AND iddepartamento='"+ elPw+"'");

            if( resultadosConsulta.first() )        // si es valido el primer reg. hay una fila, tons el usuario y su pw existen
                return true;        //usuario validado correctamente
            else
                return false;        //usuario validado incorrectamente

        } catch (Exception e)
        {
            return false;
        }

    }
    private void marcafv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcafv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcafv1ActionPerformed

    private void marcafv1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcafv1FocusGained
        marcafv1.removeAllItems();
        conexioninicio ci=new conexioninicio();
        ci.conectar();
        try{
            Connection con=DriverManager.getConnection(ci.getURl(), ci.getLogin(), ci.getPassword());
            //  System.out.println("Conexion a la base de datos cliente realizada con exito! ");
            Statement stmt=con.createStatement();

            ResultSet rs= stmt.executeQuery( "SELECT iddepartamento,nombredep FROM tienda.departamento ;");
            //obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd=rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas=rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las columnas

            // Creando las filas para el Jtable
            while(rs.next()){
                Object[] fila=new Object[cantidadColumnas];
                for(int i=1;i<cantidadColumnas;i++){
                    marcafv1.addItem(rs.getObject(i+1));

                }

            }
            rs.close();
            con.close();

        } catch(Exception e) {

            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",
                    JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_marcafv1FocusGained

    private void marcafv1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcafv1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_marcafv1FocusLost

    private void marcafv1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_marcafv1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_marcafv1AncestorAdded

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        conexioninicio ci = new conexioninicio();
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgregarAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con=null;

        try{
            if  (jTextField1.getText().length() > 0) {
                con=DriverManager.getConnection(ci.getURl(), ci.getLogin(), ci.getPassword());
                String cadenasql = "insert into tienda.departamento(iddepartamento,nombredep) values(NULL,'"+ jTextField1.getText().toUpperCase()+"')";
                Statement stmt = con.createStatement();
                stmt.executeUpdate(cadenasql);

                JOptionPane.showMessageDialog(null,"Registro exitoso!","",JOptionPane.ERROR_MESSAGE);
               jTextField1.setText("");
            } else JOptionPane.showMessageDialog(null,"Ingrese el nombre del departamento","",JOptionPane.ERROR_MESSAGE);
        }

        catch(SQLException e) {

            JOptionPane.showMessageDialog(null,"La marca ya esta registrada","Error",JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conexioninicio ci = new conexioninicio();
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgregarAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con=null;

        try{

            if  (cbfv.getText().length() > 0 && preciofv.getText().length() > 0&& medidafv.getText().length() > 0) {
                con=DriverManager.getConnection(ci.getURl(), ci.getLogin(), ci.getPassword());
                String cadenasql = "insert into tienda.articulo(codigobarras ,idmarca ,nombreart,descripcion ,iddepartamento,medida,precio) values('"+cbfv.getText().toUpperCase()+"','"+( marcafv.getSelectedIndex()+1)+"','"+namefv.getText().toUpperCase()+"','"+ desfv.getText()+"','"+( marcafv1.getSelectedIndex()+1)+"','"+ medidafv.getText()+"','"+ preciofv.getText()+"')";
                Statement stmt = con.createStatement();
                stmt.executeUpdate(cadenasql);
                marcafv.removeAllItems();
                JOptionPane.showMessageDialog(null,"Su producto se ha registrado satisfactoriamente","",JOptionPane.ERROR_MESSAGE);
            }

            else{
                JOptionPane.showMessageDialog(null,"Hay campos indispensables para registrar el producto","Error",JOptionPane.ERROR_MESSAGE);
            }

        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }       // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cbfv;
    private javax.swing.JTextField desfv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton24;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JComboBox marcafv;
    private javax.swing.JComboBox marcafv1;
    private javax.swing.JTextField medidafv;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField namefv;
    private javax.swing.JTextField nombmarfv;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField preciofv;
    // End of variables declaration//GEN-END:variables

}
